### ISSUE TITLE
Feature request: track warfront weekly quests or completion

### ISSUE THREAD

**Issue by HaraiUlfsark** [teelolws/Altoholic-Retail#116]
Hello, I'm finding the task manager so useful lately but it feels a little limited, would it be possible to track weekly quests or events?
I'm mostly thinking about the Warfronts quests in this case but perhaps it may have other uses (legion dalaran archaeology quests? anything new in shadowlands?)

Thank you

**Comment by teelolws** [comment]
I don't really do that stuff so I can't test it. Can you not track them by tracking the daily quests? I don't really have a way to detect which dailies are up that day, as I don't have a database of quests with their schedules built in to Altoholic.

**Comment by HaraiUlfsark** [comment]
Oh I understand that perfectly, I'm only tracking the completion of the dailies, not if they're up or not, for example during brewfest I had it tracking the 3 different invasions and that worked flawlessly (of course each character could only complete one of the invasions daily).
The issue is that the [warfront](https://www.wowhead.com/quest=56136/heroic-warfront-the-battle-for-stromgarde) quests are not normal dailies (with the blue questionmark and, well, repeatable daily), they are more like the [call to arms](https://www.wowhead.com/quest=56648/call-to-arms-nazjatar) quests or [against overwhelming odds](https://www.wowhead.com/quest=54978/against-overwhelming-odds) and as such the addon is correctly not detecting it as a daily quest (I've tried it this last stromgarde warfront a few days ago)
One alternative, and I dont know if its possible, would be a kind of advanced option to add a custom quest using its ID and then the user would have to know the ID instead of the addon trying to detect your completed quests, in this case I would have to enter 57960 and 56136 in the manage window for the two warfronts
And again thank you for your time

**Comment by teelolws** [comment]
Allright, I've got this ready for testing on the PTR or Beta. I've added a box to DataStore_Quests to let you enter a Quest ID to force it to track that quest.

![image](https://user-images.githubusercontent.com/49792789/95567136-040cbc80-0a7f-11eb-831a-a1bd0452b458.png)

This HAS to be done in DataStore because the quests are not normally tracked in the Quest Log when they're completed, so DataStore doesn't detect if the quest is completed unless I specifcally tell it to check that Quest ID. This is how I've tracked emissary quests and mechagon quests - I made a list of Quest IDs in DataStore and told it to track them. So now, you have the option to add more hidden quests for it to track.

This should let those dailies appear under Tasks when you've completed that quest on that character.

Its up for testing: https://github.com/teelolws/DataStore_Quests/commit/37c35637db0dbc25dc8c6e96b6f1d529834d38d9 and https://github.com/teelolws/Altoholic-Retail/commit/df5eebf52eb91def22b7c96ae815b4e5556369b2

I wasn't able to find a quest to test this with on the PTR, though. People aren't really doing the Warfronts on the PTR. So we might have to wait until next week to find out if it works.

**Comment by HaraiUlfsark** [comment]
With Darkshore Warfront live again I had the opportunity to test it. So it seems I was able to add those quests using the hidden tracker you implemented, I even checked the lua file generated for my account and they appear like this
 
		["Options"] = {
			["ManuallyTrackedQuests"] = {
				[56136] = true,
				[57960] = true,
			},
So I proceed to do the Warfront and hand in the quest, but so far in the manager window it still says my character had not completed any daily quests yet, and in another character it only shows the daily quests I had completed with him (maybe it needs its own category?)
I will try to populate it with other "regular but repeatable quests" like the call to arms ones and against overwhelming odds to see how and if it will work with any of those
Once again thank you for your effort

**Comment by teelolws** [comment]
Boo. Oh well, I'll take a look.

**Comment by teelolws** [comment]
Allright, got it working.
![image](https://user-images.githubusercontent.com/49792789/96182581-2c6e4c80-0f92-11eb-9123-8cb3d83a5d7c.png)

![image](https://user-images.githubusercontent.com/49792789/96182610-33955a80-0f92-11eb-9219-62049daabfb3.png)

Fixed in: https://github.com/teelolws/Altoholic-Retail/commit/e9772589a45c8f0130caece65002bfc201bdd0a8

**Comment by HaraiUlfsark** [comment]
Thats is perfect, thank you so much
![image](https://user-images.githubusercontent.com/72536223/96192479-803e4e80-0f1c-11eb-96be-7aa07d71ae45.png)
