### ISSUE TITLE
[Feature Request] Ungroup by Realm

### ISSUE THREAD

**Issue by berryhedgehog** [teelolws/Altoholic-Retail#12]
Is it possible to somehow ungroup the Summary tab data by realm? It only sorts within each group of 2-3 characters per realm. I'd like to be able to see all my characters in, for example, Level order or Played order regardless of realm. If the realm still needs to be displayed maybe it could be part of the character name like it is in chat: Character-Realm.

![SortByLevel](https://user-images.githubusercontent.com/62520814/77259963-d0895280-6c52-11ea-9ba7-b4a58cbd8c7f.PNG)

**Comment by teelolws** [comment]
I could do this, BUT, if I do, you won't be able to see the characters realm on that screen. You sure you want that?

**Comment by berryhedgehog** [comment]
I'd probably still use it, but I don't think enough people would to make it worth coding. Would it be possible to put the Realm in the box that shows on-hover over the Name?

**Comment by teelolws** [comment]
What I might do is add another option to this: 
![image](https://user-images.githubusercontent.com/49792789/77260603-f6176a00-6ced-11ea-8e98-e28ce90735c2.png)

I'll call it ... uh.... "All realms (Hide Realms)".

I'll just add the realm to the tooltip for all characters no matter what. It should have been there already, imo. Guess that wasn't important to Thaoky.

**Comment by berryhedgehog** [comment]
That sounds perfect. Thank you.

**Comment by teelolws** [comment]
Allright, got it. Took me a few hours of trying to figure out his sorting function and such.

Here it is, individual realms removed from the list, sorted by Name, with the Realm on the tooltip: 
![image](https://user-images.githubusercontent.com/49792789/77266564-a98b5900-6d04-11ea-94f8-c6327af0e4f1.png)

And heres a character I haven't logged into since adding the new code, realm isn't shown because I haven't logged into it to save that value yet:
![image](https://user-images.githubusercontent.com/49792789/77266584-b90aa200-6d04-11ea-94fc-a3d6a5c498d4.png)

I'll push the changes onto the main github page soon. I won't do an individual release for this.

**Comment by berryhedgehog** [comment]
Nice! I'll keep an eye out for it.

**Comment by teelolws** [comment]
Its up, grab the changes off the main page here
![image](https://user-images.githubusercontent.com/49792789/77267896-f5400180-6d08-11ea-9670-e55206d60dff.png)

**Comment by berryhedgehog** [comment]
I tried to do a donation via Curse, but I didn't notice at first it went to Thaoky. Do y'all keep in touch, or that's just lost to the ether?

**Comment by teelolws** [comment]
Thats lost, though you might be able to do a paypal reversal? The only way to support **me** is via my patreon link, everything else goes to Thaoky. He is collecting 100% of the Curseforge points, too.

**Comment by berryhedgehog** [comment]
Ok, I'll try to dispute it. I don't like to have a monthly subscription, so I'll just do one month for the full amount and then cancel.

**Comment by teelolws** [comment]
Sounds good. Just saw the donation, thanks for that! Very generous.

**Comment by teelolws** [comment]
If you want to hop onto my discord server, make sure to grab the link off my Patreon page before you unsubscribe.
