### ISSUE TITLE
French translation sharing account

### ISSUE THREAD

**Issue by Fylinss** [teelolws/Altoholic-Retail#158]
Hello,
Here the french translate for the sharing account part.

"Request Content" : "Demander du contenu"
"Cancel" : "Annuler"
"Transfering item" : "Transfert d'article"
"Available Content" : "Contenu disponible"
"Size" : "Taille"
"Up-to-date" : "À jour"
"Entire Database" : "Base de donnée entière"
"Ongoing" : "En cours"

**Comment by teelolws** [comment]
Damn, that button names kinda long: 
![image](https://user-images.githubusercontent.com/49792789/98434210-8a75f600-2132-11eb-8e35-fe193954dcf5.png)

![image](https://user-images.githubusercontent.com/49792789/98434222-a5486a80-2132-11eb-917f-1e6d9a041172.png)

Turns out I didn't need to translate "Cancel" as I found it in GlobalStrings already.

Rest of them added in: https://github.com/teelolws/Altoholic-Retail/commit/5d50596ba269f3b8be686e0576ab5bab1ca3f163
