### ISSUE TITLE
Altoholic and Auctionator compatibility

### ISSUE THREAD

**Issue by addonaddict** [teelolws/Altoholic-Retail#160]
Hello, I left this bug over at Auctionator too as im not aware which addon is causing this
I notice that undermine journal works with Altoholic, but auctionator does not, i am hoping auctionator can get incorporated too
See below for what I wrote @ auctionator:

Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

Tooltips within Altoholic addon do not show auctionator data such as auction house price for an item
![image](https://user-images.githubusercontent.com/73442541/98046657-9b53fe00-1df8-11eb-83e7-244fa0ff7cd8.png)

## Steps to Reproduce

Install auctionator and Altoholic-Retail (Teelo's Fork), open guild bank (or any other altoholic frame), then hover over any item. Auctionator does not work with altoholic tooltips.

## Loaded Addons

Altoholic-Retail (Teelo's Fork) + Auctionator

## Back Trace (LUA Error Output)

(Not a UI error)

Is this something that will be fixed/added?

Thank you

**Comment by teelolws** [comment]
Using GameTooltip:SetItemByID instead of GameTooltip:SetHyperlink will make it easier for other addons to watch the tooltip. I've submitted a Pull Request to Auctionator with the change they will need to make to fix this.
https://github.com/teelolws/Altoholic-Retail/compare/5d16de9b287d...f5bdeb3518b5
