### ISSUE TITLE
Missions

### ISSUE THREAD

**Issue by givmeafreknname** [teelolws/Altoholic-Retail#161]
I've noticed over the last few days that for the Garrison, Class Hall and War Campaign that the "In Progress" portion rarely, if ever, progresses to the "Completed Missions" section or don't even show up on the "In Progress" or "Completed Missions" at all. Also for the Class Hall and War Campaign the "Available Missions" doesn't update until you log on to that toon and open the actual mission table.

**Comment by teelolws** [comment]
DataStore_Garrisons doesn't currently store the time when a mission was started, or some other way of calculating how much time is left on the mission.

I might be able to get that from C_Garrison.GetMissionTimes, but theres no documentation on that function anywhere. This ones going on the "needs research" list.

**Comment by teelolws** [comment]
Scratch that, I found a solution.

While I was there, I noticed that since I increased the followers to 5 for Shadowlands, its overlapping on top of the time remaining:
![image](https://user-images.githubusercontent.com/49792789/98605342-1a41bd00-234a-11eb-8f77-5701030aaf96.png)

Shoved it 40 pixels to the right:
![image](https://user-images.githubusercontent.com/49792789/98605440-4e1ce280-234a-11eb-9f8c-ea12edae00a7.png)

It might have issues later on with missions that have two rewards. Will have to see when I can find one.

New patch going up soon. Let me know if it solves your problem.

**Comment by givmeafreknname** [comment]
It seemed to have been working when I logged on a couple hours ago, but at some point after I saw your message it went back to being broken. For example, on 1 toon I have 5 missions that are finished at the Garrison, but they don't show up in the "In Progress" or "Completed Missions" and didn't reappear until I opened the table at the Garrison. Maybe it's a cache problem? I know nothing about addons so just spouting words here. If there's some way for me to post some data that would help, let me know.

**Comment by teelolws** [comment]
You're right, its wiping the in-progress missions on login for some reason. I'll keep investigating.

**Comment by teelolws** [comment]
Delaying the login garrison scan seemed to fix it for me. Let me know if this works. https://github.com/teelolws/DataStore_Garrisons/commit/dda8c12b5dd18d54c62c09f6cbc5ebd15c99737d

**Comment by givmeafreknname** [comment]
Been logged on a few hours now and still seems to be working. Thanks for the quick fix! I'll let you know if it happens again but I think we can call this a win.
