### ISSUE TITLE
Breaking other addon

### ISSUE THREAD

**Issue by lonewolf215** [teelolws/Altoholic-Retail#188]
The last update of this broke another addon that I was using, TRP.

**Comment by teelolws** [comment]
I don't see anything wrong with it.

**Comment by lonewolf215** [comment]
How it's not wrong that after an update it breaks other add-ons?

**Comment by teelolws** [comment]
Its not breaking anything.

**Comment by lonewolf215** [comment]
There is a clear compatible issue, if I use the non updated version the other add-on works. After the last update, it doesn't

**Comment by teelolws** [comment]
You are mistaken. I'm using both right now, there are no issues.

**Comment by gOOvER** [comment]
> There is a clear compatible issue, if I use the non updated version the other add-on works. After the last update, it doesn't

Post a Log or never happends ;)

**Comment by onoira** [comment]
> Its not breaking anything.

... _anymore_: <https://archive.is/8ujtd>

**Comment by teelolws** [comment]
> 
> 
> > Its not breaking anything.
> 
> ... _anymore_: https://archive.is/8ujtd

404 Error.

**Comment by lonewolf215** [comment]
> 
> 
> > Its not breaking anything.
> 
> ... _anymore_: https://archive.is/8ujtd

....this was made intentional?...

**Comment by lonewolf215** [comment]
> 
> 
> > There is a clear compatible issue, if I use the non updated version the other add-on works. After the last update, it doesn't
> 
> Post a Log or never happends ;)

Noob on this, barely know how to detect problems and less to speak in english cause I am a idiot non english native. But the link actually shows my problem. 

As I update an addon, I always do 3 backups of my addon data, after updating I activate one addon at the time and check if there was something, but once I activated trp things started to fail. A wipe wasnt a problem, but, each time I tiped, and log of a character, data was wipping again. Which took me to test with a roll back, I though it was a compatibility issue, like both add-ons competing for a file or similar. No idea on this shit, ...but its an intended change? So I dont know if.

**Comment by TrinitysEnd** [comment]
Yes it was. 
TRP's Dev commenting on it: https://twitter.com/Solanya_/status/1342992364563017733. 
Picture link of the code and the unobfuscated code: 
![image](https://user-images.githubusercontent.com/37823216/103165741-36050380-47d0-11eb-9c38-a35032d4dc15.png)

This was in DataStore, which is part of Altoholic. The github for DataStore was taken down already and despite his removal of the update on Curseforge, they will still have the records of the update and will see that the code violates two of the rules. 1. Malicious code meant to ruin or hinder user experience. 2. Hiding code to make it so most cannot understand or realize the maliciousness of the code. Though probably also a third, his constant claim he didn't do this and attempt to hide the evidence.

**Comment by filliph** [comment]
@teelolws what is wrong with you? 

You need to post a statement about this on the main add-on page on CurseForge where you admit what you did, explain the full story that led up to you deciding to do this, and apologise.

There is no excuse for what you did and you need to own it, if you are to have any chance of regaining the trust of the community.

**Comment by WFrancois** [comment]
Heyas,

Any insight on what happened for this part of code to be in the addon ?

**Comment by TrinitysEnd** [comment]
> 
> 
> Heyas,
> 
> Any insight on what happened for this part of code to be in the addon ?

From what I've seen passed around and shared, there was a discussion going on in a discord separate than the TRP and Altoholic ones. This topic was about OW Shareholders or the like, I don't know the details of. But one of the mods there asked for the discussion to be moved to Off-topic. Teelo commented that the Mod should Fuck Off because it was all on topic (I think) and that the mod should keep out of it. At this comment, a member of the TRP3 team who happened to also be a mod on this discord, reached out to Teelo to ask him to refrain from using such language as it was impolite and unnecessary. The reaction to the PM was not nice, referring to the team member as Internet Police and insulting. Unrelated to the team member's reach out, another mod of that discord removed Teelo's color role (it provided no benefit than a color). He then sent the TRP team member a message declaring war. Soon after, this commit was pushed that was mentioned above in my other message. While I've seen screenshots of the conversation, they aren't mine to share, but you can likely find a few of them at least floating on Twitter (I've seen at least two of them but not the DMs there). The info on the DMs comes from the TRP Team member themselves (with pictures but again not mine to share).

**Comment by teelolws** [comment]
Well I can see this conversation is unproductive. If you don't like this addon, then don't use it. I was never gaining anything from any of you anyway, so I have no reason to care for any of you. I only took over this project because nobody else would, now, there will not be any more updates to it because noone else wants to maintain it.
