### ISSUE TITLE
Account Sharing -> Ongoing silently fails to add character

### ISSUE THREAD

**Issue by tcarmichael** [teelolws/Altoholic-Retail#191]
It looks like the function is trying to access old EditBox names. When I change the two `EditBox::GetText()` calls to point to the correct parent frame, the feature works.

If this is new (and fantastic) feature is fully released, you may want to consider updating #73 with setting up Ongoing account sync.

https://github.com/teelolws/Altoholic-Retail/blob/cb4ab419bce014da24ec16c3e35d958635440174/Altoholic/Frames/AccountSharing.xml#L779

https://github.com/teelolws/Altoholic-Retail/blob/cb4ab419bce014da24ec16c3e35d958635440174/Altoholic/Frames/AccountSharing.xml#L846

https://github.com/teelolws/Altoholic-Retail/blob/cb4ab419bce014da24ec16c3e35d958635440174/Altoholic/Frames/AccountSharing.lua#L992-L993

**Comment by teelolws** [comment]
Right. I changed the frame name from "Tab2" to "OngoingTab" at some point, must have missed that reference. I don't have two accounts so its a section I can't easily test.

Fixed in: https://github.com/teelolws/Altoholic-Retail/commit/25a4eaf05c0a686733583eb50eb23a5f539db2d9

However, please keep in mind: Thaoky has recently removed me from the project on Curseforge, and intends to release a version of Altoholic there that removes most of the features I have added over the last year.

My Fork will continue to be available here on Github, so the choice is yours which version you want to use going forward. If you choose to use my fork, make sure to setup your Addon Manager to ignore any projects on Curseforge or WoWInterface!
