### ISSUE TITLE
[FR] Add Auction expired reminder similar to expiring mail

### ISSUE THREAD

**Issue by fzarr** [teelolws/Altoholic-Retail#194]
Is is possible to add an option so that Altoholic will alert (chat message / popup box) when auctions have expired since x days ago (number of days is configurable)?

**Comment by teelolws** [comment]
When Auctions expire, they turn into Mail and are removed from the Auction database. That Mail is tracked, even if you haven't been to the Mailbox yet, as mail from the AH with an unknown item in it (since it doesn't know if the auction sold or not).  So you can instead use the Mail sliders to get alerts about when the mail from the AH will expire and get deleted.

The reason I don't have the option for chat notices when your auctions expire is its probably going to be very very spammy. I'd rather not have 1000 lines of "your auction expired while you were offline!" when I login!
