### ISSUE TITLE
Tradeskills - Some recipes showing an X

### ISSUE THREAD

**Issue by TwoTailedFox** [teelolws/Altoholic-Retail#34]
Most recipes listed working, but some blind spots, like Truesteel Ingot, among others, remain.

**Comment by teelolws** [comment]
I'll just have to update LibCraftInfo with these as they're found.

But Truesteel Ingot is there, its just listed twice for some reason. Looks like a version of it was removed around 8.1ish.

This should sort that out:
![image](https://user-images.githubusercontent.com/49792789/83707056-3a6ba280-a66d-11ea-8c0f-d629eaa6a58c.png)

Fixed in: https://github.com/teelolws/Altoholic-Retail/commit/473cca644d1722830783510aa82e1b1665e2c34a
