### ISSUE TITLE
Dungeon Finder - Broken

### ISSUE THREAD

**Issue by TwoTailedFox** [teelolws/Altoholic-Retail#35]
Shows no data at all. Also needs to be reorganised as Blizz no longer has separate 10/25 man raid achievements, instead offering LFR/Normal/Heroic as one combined achievement tier, and Mythic as a separate tier on a per-boss basis.

**Comment by teelolws** [comment]
You're referring to Grids->Dungeon Finder, right?

![image](https://user-images.githubusercontent.com/49792789/83619194-a0a9e400-a5df-11ea-92d7-61821a575206.png)

I looked at this a few weeks ago, and didn't touch it because I don't understand what its supposed to be tracking! I *think* its tracking whether you are locked to the dungeon, rather than acheivements.

**Comment by TwoTailedFox** [comment]
You could well be right, but if that's the case, a more minor rework is required, as 10 and 25 player instances on the same difficulty now share the same lockout, as well as adding all remaining WoD instances, plus Legion and BfA ones. For the black spaces, it might be an idea for it to anyway show a roster of bosses for that dungeon/raid for a quick reference.
