### ISSUE TITLE
Nazjartar Emissary, Assults, Daily Visions, Mythic Keys...

### ISSUE THREAD

**Issue by Nickster76** [teelolws/Altoholic-Retail#38]
Is this where I would go to ask if we'll ever see Nazjartar Emissary added to the Emissary Quests list, and also Assaults, Daily Visions, maybe M+ key status kinda like Astral Keys does it?

**Comment by teelolws** [comment]
The Alliance Naz'jatar Emmissary was tracked, I had the wrong QuestID for the Horde one. Fixed in: https://github.com/teelolws/Altoholic-Retail/commit/f41cdcb90b1038d652225f1841592ae698eea25a

Mythic Plus tracking is in there:
![image](https://user-images.githubusercontent.com/49792789/83718310-ee2e5b80-a688-11ea-938f-147e052486ff.png)
Is that missing information you would like tracked?

For Daily Visions, just track the Daily Quest associated with it:
![image](https://user-images.githubusercontent.com/49792789/83719131-8711a680-a68a-11ea-920d-5c13c5f8be8b.png)

Assaults are on my list of things to make. It'll be another Grids section.

**Comment by Nickster76** [comment]
Oh wow, thanks for such a quick response. i love Altoholics, thanks for all the work you put into it. Do you have a Patreon or something?


Thanks,
Nick

________________________________

**Comment by Nickster76** [comment]
I'm Alliance, I don't see Nazjartar, only see Kirin Tor, Armies of legionfall, Proudmoore, Storm's Wake, and The Dreamweavers. Also I don't know how to apply the fix to the LUA file, I don't see those lines in the DataStore_Quests/DataStore_Quests.lua<https://github.com/teelolws/Altoholic-Retail/commit/f41cdcb90b1038d652225f1841592ae698eea25a#diff-ef53a18471cf0051114b6a9f574d7cda>


________________________________

**Comment by teelolws** [comment]
Grab the latest files off the main page here:

![image](https://user-images.githubusercontent.com/49792789/83720831-fccb4180-a68d-11ea-8a85-f822bde48a61.png)

I'm still working on another part of the addon, which is a lot of work, so I probably won't be uploading these changes to Twitch for a few more days.

**Comment by Nickster76** [comment]
Ooh, Just found out I'm on version 8.3.006 by thaokyaltoholic, whoops. How do I get yours? I got his from Twitch.

________________________________

**Comment by teelolws** [comment]
https://www.curseforge.com/wow/addons/altoholic-retail

**Comment by teelolws** [comment]
Added the assaults and Mechagon daily to Emmissaries. They're having issues, though. I'll look into it another day.

![image](https://user-images.githubusercontent.com/49792789/83721606-86c7da00-a68f-11ea-8c93-6948143c1270.png)

As for my Patreon, yup! Its the Sponsor button at the top of this Github page.
