### ISSUE TITLE
Add AutoSync functionality on login and/or periodic interval.

### ISSUE THREAD

**Issue by Charles082986** [teelolws/Altoholic-Retail#51]
As a user with multiple (5) accounts, I would like Altoholic to remember my characters and accounts and automatically sync information at periodic intervals so I don't have to make 4 requests from each account (20 requests in total to fully update all accounts with data from all other accounts).
A slash command to instruct altoholic to refresh data from all linked accounts would also be nice.

Phase 1: Create a "history" option that remembers all previously sync'd accounts, characters, and requested data, and a history configuration panel to manage this data.
Phase 2: Create a /altoholic refresh [accountName] command that triggers the sync process.
Phase 3: In the history configuration panel, add a checkbox indicator for automatic syncing.  Every 15 minutes (configurable), when the user is not in combat, loop through and request a refresh from each indicated account.

**Comment by teelolws** [comment]
Its on my list of features to add but will take a considerable amount of work and not a priority to me.

**Comment by Charles082986** [comment]
Mind if I fork and work on it?  I'm not great with Lua frames so the UI might need some massaging, but I know the syntax well enough to handle the application layer code.

**Comment by teelolws** [comment]
Sure. The DataStore modules would need a ton of redesign. Their current methodology is to just capture events that could change its database, wipe the entire database and rescan it all over again.

To do constant updates, we would have to switch to a model of capturing updates to the database. I can't just be constantly re-sharing the entire database, as addons are throttled too much for that.

For an example, DataStore_Crafts:

When a player crafts something, an event triggers. Datastore captures this event, wipes the entire profession table for that player and rescans it again.
There are various reasons. Changes in skillup "difficulties". Discovery bonuses. Profession cooldown. A few others I'm not thinking of.
Since the API doesn't give us a direct way to get what just changed for most things, we would have to rescan the profession then compare the differences to the previous one, and send the changes off to AccountSharing.

**Comment by Charles082986** [comment]
Let's cross that bridge when we get to it.  For Phase 1, what we need is:
- Save AccountShare Request Information
    - Account Name
    - Character Name
    - Information Requested
- Create a management panel for this information
    - Edit which information should be requested when it is requested.
    - Group characters by account.
    - Request button to automatically issue a new request.

For multiboxers, this reduces the completion of n(n-1) share requests down to just n(n-1) clicks, which is already a huge QoL improvement.

**Comment by teelolws** [comment]
I've made a start with my idea for regular data syncing on Classic and will port it to retail in the coming days when I get a chance: https://github.com/teelolws/Altoholic-Classic/compare/5d5c9a974442...f750ee9e5072

I'm focussing only on getting inventory management working.

For your multiple characters issue, I want to make it sync data using a hidden addon channel, but that won't work for multiboxers on retail who have their characters on different servers so I will need to find another way.

**Comment by teelolws** [comment]
Added some autosyncing to Retail: https://github.com/teelolws/Altoholic-Retail/compare/7a8b45fbee30...d59c005eba62

Give it a try.

I can only directly send addon messages to players on the same server or connected servers. For multiboxers who have characters on other servers, I plan to add transmitting via party or raid instead. The characters and servers will still need to be registered, though.

Another future option is to add an option to automatically start sharing upon login. Not yet, though, because players will get a bunch of "that player is not online" spam.
