### ISSUE TITLE
Fraction filter for "Allianz" fraction not working correctly with german translation on summary page

### ISSUE THREAD

**Issue by nevermiii** [teelolws/Altoholic-Retail#53]
When starting WoW client with german settings (audio and text) the fraction filter on the summary page is not working correctly.
When selection "Allianz" no chars are shown. "Horde" works fins. Also "Both" is showing the correct chars.
When I start the WoW client with english setting all works fine.

I treid to find it in the code, but no luck :-)

Pics included:
![alto_all](https://user-images.githubusercontent.com/67972326/86819634-3aa1f800-c088-11ea-915b-799d7d2e97e0.PNG)
![alto_alli](https://user-images.githubusercontent.com/67972326/86819640-3d9ce880-c088-11ea-8b13-4f3429dbf943.PNG)
![alto_horde](https://user-images.githubusercontent.com/67972326/86819651-3fff4280-c088-11ea-9545-d51118cd289d.PNG)

**Comment by teelolws** [comment]
Looks like DataStore stores the factions in English, and only converts them to your local language when they get a colour added:

![image](https://user-images.githubusercontent.com/49792789/86846145-9d35db00-c0fe-11ea-9c93-ebce0fbdb787.png)

So for the faction filter there, it was comparing the English faction name against your local faction name:

![image](https://user-images.githubusercontent.com/49792789/86846235-b76fb900-c0fe-11ea-9cce-befe47ac2711.png)

The only reason Horde worked for you is because "Horde" is the same in English and German.

This makes it a simple enough fix: instead of pulling FACTION_ALLIANCE and FACTION_HORDE, which are constants defined by Blizzard and change based on your game language, I'll just hard-code "Alliance" and "Horde" instead, since the value they're compared against will always be in English:

![image](https://user-images.githubusercontent.com/49792789/86846378-e9811b00-c0fe-11ea-8e07-0b6db9a0b441.png)

![image](https://user-images.githubusercontent.com/49792789/86846605-336a0100-c0ff-11ea-8f66-7e540852c5e5.png)

Fixed in: https://github.com/teelolws/Altoholic-Retail/commit/19df2b5414de42b0600828b33f7da6b1e0acf75b
