### ISSUE TITLE
Achievments missing + Achievments "grouping"

### ISSUE THREAD

**Issue by Garnthrax** [teelolws/Altoholic-Retail#68]
1) Noticed that there missing achievments in "Expansion Features -> War Effort" - missing are ones for Darkshore, ones for Heroic versions of Warfronts + one of Stromgarde achivments is duplicated (Troops one)

2) Other situation is behavior of Achievments in "Expansion Features -> Visions of N'zoth" with progression Achievments like completed vision with 1, 2, ... 5 masks only highest completed and next incomplete show which after you complete 5mask run on one character prevents tracking your progress on other characters as you only see completed/incomplete 5 mask run and not how high mask run you managed (noticed same behavior on few other similar achievments like Most Horrific...)
Old progression Achievments show all lesser completed/incomplete - best example is "Level 10", "Level 20" ... "Level 120"
While new version was likely more advanced/tricky to code older version showing ALL achievments seems much better for progress tracking across chars

3) following is not really something worth losing time about, more something to keep in mind for future additions. For some reason with Island Expedition Achievments they are listed in order Heroic-Mythic-Normal-PvP instead of more logical Normal-Heroic-Mythic-PvP

**Comment by teelolws** [comment]
For 1. it looks like an achievement slipped into the addon that was never added to the game: https://www.wowhead.com/achievement=12871/prepared-for-war#news causing the rest of it to break.

For 2. it pulls that list directly from the Achievements frame. I'll have to manually code all the individual achievement IDs.

For 3. I fixed the order and noticed the "new" island expeditions werent listed properly.

Fixed in: https://github.com/teelolws/Altoholic-Retail/commit/038eac2178ee6a51081e9e9c77ee808e366828e2
