### ISSUE TITLE
Account sharing isnt working

### ISSUE THREAD

**Issue by Cealian** [teelolws/Altoholic-Retail#7]
Im trying to get the account sharing to work. Have not worked since 8.3. This is the error currently 

`11x DataStore\DataStore-r67.lua:723: assertion failed!
[string "=[C]"]: in function `assert'
[string "@DataStore\DataStore-r67.lua"]:723: in function `GetModuleLastUpdate'
[string "@Altoholic\Frames\AccountSharing.lua"]:680: in function `GetDate'
[string "@Altoholic\Frames\AccountSharing.lua"]:588: in function `Update'
[string "@Altoholic\Altoholic-r192.lua"]:404: in function `ScrollFrameUpdate'
[string "@Altoholic\Frames\AccountSharing.lua"]:770: in function `Update'
[string "@Altoholic\Comm.lua"]:369: in function `?'
[string "@Altoholic\Comm.lua"]:166: in function `?'
[string "@Altoholic\Comm.lua"]:131: in function `?'
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@Ace3\AceComm-3.0\AceComm-3.0-12.lua"]:218: in function `OnReceiveMultipartLast'
[string "@Ace3\AceComm-3.0\AceComm-3.0-12.lua"]:256: in function <Ace3\AceComm-3.0\AceComm-3.0.lua:246>`

**Comment by teelolws** [comment]
Hi, can you open up Datastore\\Datastore.lua, go to line 722, and add this code:

`     if (type(module) ~= "table") then print("Error: module isn't a table. Its value is: ", module) end`

Try the account sharing again and see what it outputs in chat when you get the error.

I suspect you have one of the Datastore addons disabled or not installed at all. Which is all fine for the rest of the addon, but Account Sharing isn't coded in a way that can deal with a missing Datastore Module. 

Do you, for example, normally just remove the Datastore_Garrisons module? I do that, because I don't care about my Garrisons anymore, and it was an easy way to stop the reminders that I have resources to collect.

**Comment by Cealian** [comment]
I noticed that DataStore_Auctions wasnt enabled on one of the characters so when i enabled it it seems to be working.
