### ISSUE TITLE
Profession recipes with cooldowns expires at wrong timing

### ISSUE THREAD

**Issue by comiluv** [teelolws/Altoholic-Retail#74]
For example, [Transmute: Herbs to Anchors](https://www.wowhead.com/spell=286547) expires on daily instance reset time, but Altoholic shows their cooldown expired at midnight, which is faulty.

**Comment by teelolws** [comment]
It seems we have just found a bug in Blizzards code.

The code I used to test it is: 

`/dump C_TradeSkillUI.GetRecipeCooldown(251808)`

Thats entirely Blizzards code. Its to get the number of seconds remaining on the transmute cooldown.

When I first ran it immediately after crafting a transmute, it looked like this:
![image](https://user-images.githubusercontent.com/49792789/89689832-50d9f700-d959-11ea-9005-18044d466d14.png)

This time is *wrong*. 59818 seconds from when I did that is midnight. So, its the wrong time pointing to midnight, like yours.

When I logged out and back in again, it looked like this:
![image](https://user-images.githubusercontent.com/49792789/89689895-76670080-d959-11ea-9a1e-8e60b5efeb09.png)

Its jumped up by about 3000 seconds, pointing to the correct time of 2am.

There is no way for my code to know when that number is correct and not correct. The only way to get this fixed is to ask Blizzard to fix `C_TradeSkillUI.GetRecipeCooldown`.

**Comment by comiluv** [comment]
Looks like this issue is going to be up here until Blizz fixes it, then 🤣

**Comment by teelolws** [comment]
Actually, another developer pointed out to me: I could just use `C_DateAndTime.GetSecondsUntilWeeklyReset` and subtract multiples of 86400 to get "seconds until daily reset".

So, good news: I can fix this.
Bad news: in 9.0.

**Comment by comiluv** [comment]
> So, good news: I can fix this.
> Bad news: in 9.0.

Hehehehehe :rofl:

**Comment by Ariskayler** [comment]
Probably doesn't matter since 9.0 is less than 2 months away but:
From: https://wow.gamepedia.com/API_time
- This function is Lua's standard os.time(), shifted into the global namespace.
-  If not given any arguments, time() will return a value based on the local clock, so it is not synchronized among clients. Consider using GetServerTime() instead if you would rather have a value based on the server clock, which IS synchronized among clients.

Currently it seems to be using time(). And I'm guessing, in my case,  it's because I'm not using Server Time on my in-game clock. I'm using Local Time.

Either way, should be ok shortly.
